### ISSUE TITLE
Is there possibility to use kotlin dsl?

### ISSUE THREAD

**Issue by alex-t0** [xword/java-npm-gradle-integration-example#1]
How this code 
```
npm_run_build {
    inputs.files fileTree("public")
    inputs.files fileTree("src")

    inputs.file 'package.json'
    inputs.file 'package-lock.json'

    outputs.dir 'build'
}
```
must be rewritten in kotlin dsl?

**Comment by gcwiak** [comment]
Yes, it works with Kotlin DSL as well. 

Your piece of code is going to look like this:
```
tasks.named<NpmTask>("npm_run_build") {
    inputs.files(fileTree("public"))
    inputs.files(fileTree("src"))

    inputs.file("package.json")
    inputs.file("package-lock.json")

    outputs.dir("build")
}
```

We also have the whole example in Kotlin DSL, I'm going to include it soon.

**Comment by alex-t0** [comment]
Thank you! Migrating to Kotlin - is a great thing! :)

**Comment by gcwiak** [comment]
Version using Kotlin DSL added.

**Comment by gcwiak** [comment]
https://github.com/xword/java-npm-gradle-integration-example/tree/master/gradle-kotlin-dsl
