### ISSUE TITLE
How to run both backend and frontend in dev mode with hotreaload?

### ISSUE THREAD

**Issue by mikhalchenko-alexander** [xword/java-npm-gradle-integration-example#2]
Is there a way to run both back-end and front-end with hot reload? The obvious way is to run BE with `./gradlew bootRun` and FE with `npm run start` and then they both will be reloaded on change. However if I add some API usage to FE with `/` root path (e.g. `GET /api/users`), it will work in production build but not when BE/FE apps are started separately because they use different local ports (BE is on 8080 and FE is on 3000 by default). Do you have any hints on this matter?

**Comment by cezary-biernacki** [comment]
In the development mode we add a servlet to the backend that proxy frontend related requests to the frontend. The servlet is slightly improved version of Jetty's ProxyServlet.Transparent. 

In your example with BE on 8080 and FE on 3000, you connect your browser to 8080, and all requests that should go to the frontend, are transparently proxied to 3000. Of course, you need to be sure that BE and FE use different paths in URLs.

**Comment by mikhalchenko-alexander** [comment]
@cezary-biernacki Thanks for the advice.
For those who will find this later, I've also found a way to solve this from FE part. You create config file which looks like this
```
./config/index.js

const config = {
    development: {
        API_ROOT: "http://localhost:8080"
    },
    production: {
        API_ROOT: "/"
    },
    test: {
        API_ROOT: "/"
    }
};

export default config[process.env.NODE_ENV];
```
And whenever you need to get current API_ROOT you do it like this:
```
./App.js

import config from './config/index';
...
<div>{config.API_ROOT}</div>
```
When we do `npm run start` it will automatically pass `development` to `process.env.NODE_ENV` and when you `npm run build` it will pass `production` to `process.env.NODE_ENV`. The third option `test` is added in order to `npm run test` not fail due to missing `API_ROOT` value. You probably may leave it blank as FE unit tests do/should not require any backend running.
